name: Render Latex PDF

on:
  push:
  
jobs:
  tex:
    runs-on: ubuntu-20.04
    steps:
    - run: sudo apt-get install texlive texlive-lang-german texlive-latex-extra
    - uses: actions/checkout@v2.3.4
    - uses: github/super-linter@v4.6.1
    - run: pdflatex doc.tex
    - run: pdflatex doc.tex
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add doc.pdf
        git commit -m 'update document' || exit 0
        git fetch && git merge && git push
