name: Render Latex PDF

on:
  workflow_dispatch:
  
jobs:
  tex:
    runs-on: ubuntu-20.04
    steps:
      - run: sudo apt-get install texlive-base
      - uses: actions/checkout@v2.3.4
      - run: latex doc.tex
      - uses: actions/upload-artifact@v2.2.4
        with:
          path: doc.pdf
